### ISSUE TITLE
koa v2 support

### ISSUE THREAD

**Issue by pleerock** [hirako2000/koa-router-multer#1]
does it support koa v2?

**Comment by hirako2000** [comment]
Yes.

**Comment by pleerock** [comment]
I afraid it does not.

``` javascript

const koa = require("koa");
const app2 = new koa();
const multer = require("koa-router-multer");
const router = new (require("koa-router"))();
const upload = multer({ dest: 'uploads/' });
router.get("/users", upload.single('file'), function (context: any, next: Function) {
    console.log("koa controller");
    context.body = "Hello Koa";
    return next();
});

app2.use(router.routes());
app2.use(router.allowedMethods());
app2.listen(3002);
```

When I access `/users` it gives me 404 - not found. However if I remove `upload.single('file'),` and access - it gives me **hello koa**

**Comment by hirako2000** [comment]
The code I see there doesn't seem to make much sense, the resource defined there accepts a GET method - it would not work for multipart uploads.

Are you able to follow the (very brief) example I provided and see if this works with your Koa 2 server ?

**Comment by pleerock** [comment]
it was a minimal reproducable example. I just changed it to post and sent a post request - same result - 404 and not found.

**Comment by hirako2000** [comment]
I suspect the request would be invalid then;
I got this working on koa v2. the client's request must be valid otherwise koa-router won't match, thus no routing found (404).

**Comment by pleerock** [comment]
client request is 100% correct. Just copy paste my example, replace get with post and send a request - it will give you 404 which is not correct.

**Comment by hirako2000** [comment]
hmm I don't see what would be wrong then. you can find a more comprehensive resource example here.[https://github.com/hirako2000/react-hackathon-board/blob/master/server/api/hacks.js](url).
I use dropZone.js to build the request. 

If you paste a request example (body and headers) I might be able confirm whether it's correct.

**Comment by hirako2000** [comment]
thinking of this, I suspect it would be due to the syntax you have opted for; although valid.
I came across various issues trying to use vanilla koa-router and multer together.
This is the reason I published this lib (for those who also insist on being able to use koa-router along with koa2 and multer)

How to solve the problem? To be honest you got to read carefully what each lib (route vs router, multer vs alternative,  etc) supports and how they integrate with other libs and the framework (koa2)
And since the docs are often not very clear, and even in movement on bleeding edge frameworks I suggest you play around until you find the lib that integrate most easily with your set up.  This is what I did. i wanted to stick to koa-router, along with koa2 using generators. koa-router-multer works very well with this.

**Comment by hirako2000** [comment]
Closing.

**Comment by SteveCruise** [comment]
The same

**Comment by SteveCruise** [comment]
No problem， it's belong to the element-ui client error.

**Comment by mkozjak** [comment]
This does not work, so can you reopen the issue?
It works if I add it to koa.use, but not if only used with a router.

Edit: koa-multer works with latest koa and koa-router. So everyone just switch to that lib.
https://github.com/koa-modules/multer

**Comment by hirako2000** [comment]
It works for me. I use it with koa-router.
What version of Koa and koa-router you using? What is the issue/error?
